[package]
name = "etoml-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc_macro = true
[dependencies]
quote = "1.0.18"
syn = "1.0.91"
